//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppGroup.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangResource_jp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResource_jp() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppGroup.Properties.LangResource_jp", typeof(LangResource_jp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   完全削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONTENT_COMPLETE_REMOVAL {
            get {
                return ResourceManager.GetString("CONTENT_COMPLETE_REMOVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   構成コピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONTENT_CONFIGURATION_COPY {
            get {
                return ResourceManager.GetString("CONTENT_CONFIGURATION_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル名一括変換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONTENT_FILE_NAME_BATCH_CONVERSION {
            get {
                return ResourceManager.GetString("CONTENT_FILE_NAME_BATCH_CONVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PCモニター に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONTENT_PC_MONITOR {
            get {
                return ResourceManager.GetString("CONTENT_PC_MONITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PDF変換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONTENT_PDF_CONVERSION {
            get {
                return ResourceManager.GetString("CONTENT_PDF_CONVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   これらのモジュールは削除できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FAILE_DELETE_MULTIPLE {
            get {
                return ResourceManager.GetString("FAILE_DELETE_MULTIPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このモジュールは削除できませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FAILE_DELETE_SINGLE {
            get {
                return ResourceManager.GetString("FAILE_DELETE_SINGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータは空です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PARAMETER_EMPTY {
            get {
                return ResourceManager.GetString("PARAMETER_EMPTY", resourceCulture);
            }
        }
    }
}
